//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToeClient.B72905 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:B72905_TicTacToe", ConfigurationName="B72905.B72905_TicTacToePort")]
    public interface B72905_TicTacToePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#setPlayerName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setPlayerName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#setPlayerName", ReplyAction="*")]
        System.Threading.Tasks.Task setPlayerNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#startGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void startGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#startGame", ReplyAction="*")]
        System.Threading.Tasks.Task startGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#mark", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string mark(int row, int column);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#mark", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> markAsync(int row, int column);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getWinnerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getWinnerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getWinnerInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getWinnerInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getTopPlayers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getTopPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getTopPlayers", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getTopPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#saveTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string saveTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#saveTime", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> saveTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getTime", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#botPlay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string botPlay();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#botPlay", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> botPlayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getLastBotPlay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getLastBotPlay();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:B72905_TicTacToe#TicTacToe#getLastBotPlay", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getLastBotPlayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface B72905_TicTacToePortChannel : TicTacToeClient.B72905.B72905_TicTacToePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B72905_TicTacToePortClient : System.ServiceModel.ClientBase<TicTacToeClient.B72905.B72905_TicTacToePort>, TicTacToeClient.B72905.B72905_TicTacToePort {
        
        public B72905_TicTacToePortClient() {
        }
        
        public B72905_TicTacToePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B72905_TicTacToePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B72905_TicTacToePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B72905_TicTacToePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void setPlayerName(string name) {
            base.Channel.setPlayerName(name);
        }
        
        public System.Threading.Tasks.Task setPlayerNameAsync(string name) {
            return base.Channel.setPlayerNameAsync(name);
        }
        
        public void startGame() {
            base.Channel.startGame();
        }
        
        public System.Threading.Tasks.Task startGameAsync() {
            return base.Channel.startGameAsync();
        }
        
        public string mark(int row, int column) {
            return base.Channel.mark(row, column);
        }
        
        public System.Threading.Tasks.Task<string> markAsync(int row, int column) {
            return base.Channel.markAsync(row, column);
        }
        
        public string getWinnerInfo() {
            return base.Channel.getWinnerInfo();
        }
        
        public System.Threading.Tasks.Task<string> getWinnerInfoAsync() {
            return base.Channel.getWinnerInfoAsync();
        }
        
        public string getTopPlayers() {
            return base.Channel.getTopPlayers();
        }
        
        public System.Threading.Tasks.Task<string> getTopPlayersAsync() {
            return base.Channel.getTopPlayersAsync();
        }
        
        public string saveTime() {
            return base.Channel.saveTime();
        }
        
        public System.Threading.Tasks.Task<string> saveTimeAsync() {
            return base.Channel.saveTimeAsync();
        }
        
        public string getTime() {
            return base.Channel.getTime();
        }
        
        public System.Threading.Tasks.Task<string> getTimeAsync() {
            return base.Channel.getTimeAsync();
        }
        
        public string botPlay() {
            return base.Channel.botPlay();
        }
        
        public System.Threading.Tasks.Task<string> botPlayAsync() {
            return base.Channel.botPlayAsync();
        }
        
        public string getLastBotPlay() {
            return base.Channel.getLastBotPlay();
        }
        
        public System.Threading.Tasks.Task<string> getLastBotPlayAsync() {
            return base.Channel.getLastBotPlayAsync();
        }
    }
}
